Hometask for Lec. 8
AlesiaRebkavets/Hometask_Lec8 pull request #1
Opened 2022-11-21 01:07 UTC by AlesiaRebkavets

2022-11-24 07:39 UTC, ezhukovskaya requested changes

2022-11-24 07:39 UTC, ezhukovskaya commented on Hometask_Lec8/Program.cs
> +            int[] massive = { 8, 7, 1, 4, 2 };
в Try catch должно лежать только то, что может завалиться с исключением, в твоём случае это 28 и 30 строки, логично будет объявление массива убрать из конструкции

2022-11-27 21:39 UTC, AlesiaRebkavets commented on Hometask_Lec8/Program.cs
> +            int[] massive = { 8, 7, 1, 4, 2 };
corrected

2022-11-28 09:35 UTC, ezhukovskaya approved these changes

2023-02-17 11:28 UTC, merged